### PR TITLE
Feature tap2 mpgh

### PR DESCRIPTION
**Pull request by mpgh**
The new TAP fit structure could replace the parallaxDE  fit with a static PSPL TRF fit using pyLIMAv1.9 and checking if the blend is constrained with a soft_l1 loss function. If blend is constrained a chisquare TRF fit is returned. If the TRF limit is reached in u0 and tE, PSPL parameters return np.nan.
The model_telescope is now following the pyLIMAv1.9 syntax, i.e. it needs to be checked if the plotter picks it up correctly.

### CODE REVIEW

**Comment by ebachelet** [comment]
I do not see any issues so far, but I will wait before accepting the PR.

First of all, we probably would like to return some extra parameters:

 res = fit_1.model_residuals(fit_1.fit_results['best_model'])
 from pyLIMA.fits import stats
 SW = stats.normal_Shapiro_Wilk((np.ravel(res[0]['photometry'])/np.ravel(res[1]['photometry'])))
 AD = stats.normal_Anderson_Darling((np.ravel(res[0]['photometry'])/np.ravel(res[1]['photometry'])))
 KS = stats.normal_Kolmogorov_Smirnov((np.ravel(res[0]['photometry'])/np.ravel(res[1]['photometry'])))

chi2_dof =  np.sum((np.ravel(res[0]['photometry'])/np.ravel(res[1]['photometry']))**2)/(len(res[0]['photometry'])-5)
fit_type = 'chi2' or 'soft_l1'

So given the amount of information we return, I am wondering if it would not be cleaner to return a dictionnary, i.e.:

fi_results = {'t0':t0,'u0':u0......,'covariance_matrix':cov etc....]

Indeed, as we discussed, it seems a good time to rebrand everything.  I add @rachel3834 to the discussion.

**Comment by rachel3834** [comment]
On a different branch, I am trying to add extra parameters to MOP to store the current-best-fit values for all binary lens parameters, plus the KS, SW etc tests.  I think since these are a set of key:value pairs in each case, I would prefer to keep them as single extra parameters for now, and store the timeseries as a ReducedDatum instead.

**Comment by rachel3834** [comment]
OK, I've pushed the updated branch so MOP now stores KW, AD, SW as extra_params, as well as the full set of binary model parameters.  These parameters should be used to store the values for for the current-best-fitting model at any given time.  So it is now up to TAP to decide which set of parameters gets stored this way, and also to store a ReducedDatum for the timeseries of these parameters. 

Assigning this back to Markus to make the appropriate changes.

**Comment by mpgh** [comment]
Parameters and normality tests are returned, but not tested locally, yet. In addition, the parameters are not added to extra_parameters which is in the separate feature branch mentioned before.

**Review by rachel3834 — APPROVED** [review]

**Pull request merged**
